const LOGIN_USER_SUCCESS = 'LOGIN_USER';
const LOGIN_USER_GOOGLE_SUCCESS = 'LOGIN_USER_GOOGLE';
const LOGIN_USER_FACEBOOK_SUCCESS = 'LOGIN_USER_FACEBOOK';
const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';

const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_ERROR";
const REGISTER_LOADING= "REGISTER_LOADING";

const SELFIE_UPLOAD_SUCCESS = "SELFIE_UPLOAD_SUCCESS";
const SELFIE_UPLOAD_ERROR = "SELFIE_UPLOAD_ERROR";
const SELFIE_UPLOAD_LOADING= "SELFIE_UPLOAD_LOADING";

const PROOF_UPLOAD_SUCCESS = "PROOF_UPLOAD_SUCCESS";
const PROOF_UPLOAD_ERROR = "PROOF_UPLOAD_ERROR";
const PROOF_UPLOAD_LOADING= "PROOF_UPLOAD_LOADING";

const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
const USER_UPDATE_LOADING= "USER_UPDATE_LOADING";
const CLEAR_UPDATE_SUCCESS= "CLEAR_UPDATE_SUCCESS";

const EMAIL_UPDATE_SUCCESS = "EMAIL_UPDATE_SUCCESS";
const EMAIL_UPDATE_ERROR = "EMAIL_UPDATE_ERROR";
const EMAIL_UPDATE_LOADING= "EMAIL_UPDATE_LOADING";
const CLEAR_EMAIL_UPDATE_SUCCESS= "CLEAR_EMAIL_UPDATE_SUCCESS";

const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS";
const EMAIL_VERIFY_ERROR = "EMAIL_VERIFY_ERROR";
const EMAIL_VERIFY_LOADING= "EMAIL_VERIFY_LOADING";

const PENDING_CHECK_SUCCESS = "PENDING_CHECK_SUCCESS";
const PENDING_CHECK_ERROR = "PENDING_CHECK_ERROR";
const PENDING_CHECK_LOADING= "PENDING_CHECK_LOADING";

const GET_USER_DETAILS = 'GET_USER_DETAILS';
const USER_DETAILS_LOADING = 'USER_DETAILS_LOADING';

const RESET_AUTH_STORE = 'RESET_AUTH_STORE';
const SET_NOTIFICATIONS_ENABLED = 'SET_NOTIFICATIONS_ENABLED';

const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
const CHANGE_PASSWORD_LOADING= "CHANGE_PASSWORD_LOADING";

const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
const FORGOT_PASSWORD_LOADING= "FORGOT_PASSWORD_LOADING";

export default {GET_USER_DETAILS, 
    LOGIN_USER_SUCCESS, 
    LOGIN_USER_FACEBOOK_SUCCESS, 
    LOGIN_USER_GOOGLE_SUCCESS, 
    USER_DETAILS_LOADING, 
    USER_LOGIN_ERROR, 
    REGISTER_SUCCESS, 
    REGISTER_ERROR, 
    REGISTER_LOADING, 
    SELFIE_UPLOAD_SUCCESS, 
    SELFIE_UPLOAD_ERROR, 
    SELFIE_UPLOAD_LOADING, 
    PROOF_UPLOAD_SUCCESS, 
    PROOF_UPLOAD_ERROR, 
    PROOF_UPLOAD_LOADING, 
    USER_UPDATE_SUCCESS, 
    USER_UPDATE_ERROR, 
    USER_UPDATE_LOADING, 
    CLEAR_UPDATE_SUCCESS, 
    EMAIL_UPDATE_SUCCESS, 
    EMAIL_UPDATE_ERROR, 
    EMAIL_UPDATE_LOADING, 
    EMAIL_VERIFY_SUCCESS, 
    EMAIL_VERIFY_ERROR, 
    EMAIL_VERIFY_LOADING, 
    PENDING_CHECK_SUCCESS, 
    PENDING_CHECK_ERROR, 
    PENDING_CHECK_LOADING, 
    CHANGE_PASSWORD_SUCCESS, 
    CHANGE_PASSWORD_ERROR, 
    CHANGE_PASSWORD_LOADING, 
    FORGOT_PASSWORD_SUCCESS, 
    FORGOT_PASSWORD_ERROR, 
    FORGOT_PASSWORD_LOADING, 
    CLEAR_EMAIL_UPDATE_SUCCESS, 
    RESET_AUTH_STORE, 
    SET_NOTIFICATIONS_ENABLED, 
    USER_LOGIN_LOADING}