const HOME_DEALS_LOAD_SUCCESS = 'HOME_DEAL_LOAD_SUCCESS';
const HOME_DEALS_LOAD_ERROR = 'HOME_DEAL_LOAD_ERROR';
const HOME_DEALS_LOAD_LOADING = 'HOME_DEAL_LOAD_LOADING';

const FAVOURITE_DEALS_LOAD_SUCCESS = 'FAVOURITE_DEALS_LOAD_SUCCESS';
const FAVOURITE_DEALS_LOAD_ERROR = 'FAVOURITE_DEALS_LOAD_ERROR';
const FAVOURITE_DEALS_LOAD_LOADING = 'FAVOURITE_DEALS_LOAD_LOADING';

const LIKE_DEAL_ERROR = 'LIKE_DEAL_ERROR';
const ADD_LIKE_DEAL = 'ADD_LIKE_DEAL';
const UNLIKE_DEAL_ERROR = 'UNLIKE_DEAL_ERROR';
const REMOVE_LIKE_DEAL = 'REMOVE_LIKE_DEAL';

const SET_ACTIVE_DEAL = 'SET_ACTIVE_DEAL';

const CHECK_AVAILABILITY_LOAD_SUCCESS = 'CHECK_AVAILABILITY_LOAD_SUCCESS';
const CHECK_AVAILABILITY_LOAD_ERROR = 'CHECK_AVAILABILITY_LOAD_ERROR';
const CHECK_AVAILABILITY_LOAD_LOADING = 'CHECK_AVAILABILITY_LOAD_LOADING';

const REDEEM_DEAL_LOAD_SUCCESS = 'REDEEM_DEAL_LOAD_SUCCESS';
const REDEEM_DEAL_LOAD_ERROR = 'REDEEM_DEAL_LOAD_ERROR';
const REDEEM_DEAL_LOAD_LOADING = 'REDEEM_DEAL_LOAD_LOADING';

const CATEGORY_DEALS_LOAD_SUCCESS = 'CATEGORY_DEALS_LOAD_SUCCESS';
const CATEGORY_DEALS_LOAD_ERROR = 'CATEGORY_DEALS_LOAD_ERROR';
const CATEGORY_DEALS_LOAD_LOADING = 'CATEGORY_DEALS_LOAD_LOADING';

const SEARCH_DEALS_LOAD_SUCCESS = 'SEARCH_DEALS_LOAD_SUCCESS';
const SEARCH_DEALS_LOAD_ERROR = 'SEARCH_DEALS_LOAD_ERROR';
const SEARCH_DEALS_LOAD_LOADING = 'SEARCH_DEALS_LOAD_LOADING';

const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
const GET_USER_NOTIFICATIONS_ERROR = 'GET_USER_NOTIFICATIONS_ERROR';
const GET_USER_NOTIFICATIONS_LOADING = 'GET_USER_NOTIFICATIONS_LOADING';
const REMOVE_USER_NOTIFICATION = 'REMOVE_USER_NOTIFICATION';

export default {HOME_DEALS_LOAD_SUCCESS,
    HOME_DEALS_LOAD_ERROR,
    HOME_DEALS_LOAD_LOADING,
    FAVOURITE_DEALS_LOAD_SUCCESS,
    FAVOURITE_DEALS_LOAD_ERROR,
    FAVOURITE_DEALS_LOAD_LOADING,
    CHECK_AVAILABILITY_LOAD_SUCCESS,
    CHECK_AVAILABILITY_LOAD_ERROR,
    CHECK_AVAILABILITY_LOAD_LOADING,
    REDEEM_DEAL_LOAD_SUCCESS,
    REDEEM_DEAL_LOAD_ERROR,
    REDEEM_DEAL_LOAD_LOADING,
    CATEGORY_DEALS_LOAD_SUCCESS,
    CATEGORY_DEALS_LOAD_ERROR,
    CATEGORY_DEALS_LOAD_LOADING,
    SEARCH_DEALS_LOAD_SUCCESS,
    SEARCH_DEALS_LOAD_ERROR,
    SEARCH_DEALS_LOAD_LOADING,
    GET_USER_NOTIFICATIONS_SUCCESS,
    GET_USER_NOTIFICATIONS_ERROR,
    GET_USER_NOTIFICATIONS_LOADING,
    REMOVE_USER_NOTIFICATION,
    LIKE_DEAL_ERROR,
    ADD_LIKE_DEAL,
    UNLIKE_DEAL_ERROR,
    REMOVE_LIKE_DEAL,
    SET_ACTIVE_DEAL,
}